# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .\ffbsimulator\win

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

  # Path to project
  PROJ_PATH: ffbsimulator

  # Path to Linux project
  LINUX_PROJ_PATH: ./ffbsimulator/linux

permissions:
  contents: read

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build Win
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: |
        echo "Current directory: $($PWD.Path)"
        echo "Working directory ${{env.GITHUB_WORKSPACE}}"
        msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - name: Display structure of produced files
      run: ls -R ${{env.SOLUTION_FILE_PATH}}

    - name: Upload Win build artifact
      uses: actions/upload-artifact@v4
      with:
        name: FFB Simulator Win x64
        path: ${{env.SOLUTION_FILE_PATH}}\${{env.BUILD_CONFIGURATION}}\FFB_Simulator.exe

  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Build Linux
      uses: threeal/cmake-action@v2.1.0
      with:
        source-dir: ${{env.PROJ_PATH}}

    - name: Display structure of produced files
      run: ls -R

    - name: Upload Linux build artifact
      uses: actions/upload-artifact@v4
      with:
        name: FFB Simulator Linux x64
        path: ${{env.LINUX_PROJ_PATH}}/FFB_Simulator
  
  build-pi:
    name: Build for ARM64
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-gnueabihf
      - name: Build PI
        run: |
          arm-linux-gnueabihf-g++ -v
          cd ${{env.LINUX_PROJ_PATH}}/src
          arm-linux-gnueabihf-g++ -O3 -g3 -Wall -c -o -fPIC "FFB_Simulator-arm64.o" "FFB_Simulator.cpp"
          arm-linux-gnueabihf-g++ -o "FFB_Simulator-arm64" FFB_Simulator-arm64.o
